[package]
name = "tokcos"
version = "0.1.1"
edition = "2023"

[lib]
name = "_tokcos"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { git = "https://github.com/pyo3/pyo3", features = ["extension-module"] }
fancy-regex = "0.10.0"
regex = "1.7.0"
rustc-hash = "1.1.0"
bstr = "1.0.1"
